<?php

use Illuminate\Support\Str;

it('can run a command line script automatically', function () {
    command('bellows launch')
        ->fromDir(base_path('../bellows-tester'))
        ->waitFor('this will never happen')
        ->waitFor('Which server would you like to use')
        ->type('bellows-testing')
        ->waitFor('App Name')
        ->type('Bellows Test')
        ->waitFor('Domain')
        ->type(Str::random() . '.linkleapapp.com')
        ->waitFor('Isolated User', 30)
        ->enter()
        ->waitFor('Repository')
        ->enter()
        ->waitFor('Repository Branch')
        ->enter()
        ->waitFor('Secure site')
        ->enter()
        ->waitFor('Continue with defaults')
        ->confirm()
        ->waitFor('Update DNS record')
        ->enter()
        ->waitFor('Configuring Ably plugin')
        ->waitFor('Select account')
        ->type('joe')
        ->waitFor('Create new app')
        ->deny()
        ->waitFor('Which app do you want to use')
        ->type('Forge It Test')
        ->waitFor('Which key do you want to use')
        ->type('Subscribe only')
        ->waitFor('Configuring BugsnagJS plugin')
        ->waitFor('Select account')
        ->type('joe')
        ->waitFor('Create Bugsnag PHP Project')
        ->deny()
        ->waitFor('Select a Bugsnag project')
        ->type('Forge It Test')
        ->waitFor('Configuring BugsnagPHP plugin')
        ->waitFor('Select account')
        ->type('joe')
        ->waitFor('Create Bugsnag PHP Project')
        ->deny()
        ->waitFor('Select a Bugsnag project')
        ->type('Forge It Test')
        ->waitFor('Enable DigitalOceanDatabase')
        ->confirm()
        ->waitFor('Database')
        ->type('forge_it_test')
        ->waitFor('Database User')
        ->type('forge_it_test')
        ->waitFor('Database already exists, do you want to continue')
        ->confirm()
        ->waitFor('User already exists, do you want to continue')
        ->confirm()
        ->exec();
});
